<a href="https://colab.research.google.com/github/VNallasami85/VNallasami/blob/master/More_Numpy_and_Pandas_Exercise_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

# A Few More Numpy and Pandas Exercises 


To edit this notebook:
- Save the notebook by selecting `Download .ipynb` from the `File` tab
- Go to [Colaboratory](https://colab.research.google.com/) and upload the notebook from the `File` tab
- Alternatively, you can import the notebook to your Google Drive and select `Open with` when you right-click. Select `Colaboratory` or `+ Connect more apps` to install Colaboratory first

#### Import Numpy and Pandas

In [0]:
import numpy as np
import pandas as pd

#### Create an array of 64 values starting with 10 and ending with 15 and assign it to x

Remember: The third parameter to linspace is the number of values to obtain from the real line interval starting from 10 to 15 in this case.

In [0]:
x = np.linspace(10,15,64)
x

array([10.        , 10.07936508, 10.15873016, 10.23809524, 10.31746032,
       10.3968254 , 10.47619048, 10.55555556, 10.63492063, 10.71428571,
       10.79365079, 10.87301587, 10.95238095, 11.03174603, 11.11111111,
       11.19047619, 11.26984127, 11.34920635, 11.42857143, 11.50793651,
       11.58730159, 11.66666667, 11.74603175, 11.82539683, 11.9047619 ,
       11.98412698, 12.06349206, 12.14285714, 12.22222222, 12.3015873 ,
       12.38095238, 12.46031746, 12.53968254, 12.61904762, 12.6984127 ,
       12.77777778, 12.85714286, 12.93650794, 13.01587302, 13.0952381 ,
       13.17460317, 13.25396825, 13.33333333, 13.41269841, 13.49206349,
       13.57142857, 13.65079365, 13.73015873, 13.80952381, 13.88888889,
       13.96825397, 14.04761905, 14.12698413, 14.20634921, 14.28571429,
       14.36507937, 14.44444444, 14.52380952, 14.6031746 , 14.68253968,
       14.76190476, 14.84126984, 14.92063492, 15.        ])

#### Create a random shuffled array of values that include the range of values from 0 to 63 and assign to a variable called indices

In [0]:
indices = np.random.permutation(64)
indices

array([43, 32,  2, 18, 14,  0, 56, 27, 61,  5, 26, 28, 49, 31, 52, 22, 36,
        3, 55,  8, 58, 25, 17, 12, 30,  6, 39, 60, 21, 51, 63, 40,  4, 48,
       19, 46, 34, 38, 50, 53, 10, 47, 44, 35, 59,  7, 11, 45, 29, 62, 23,
        9, 57, 54, 42, 37, 13, 24, 20, 15, 16, 41,  1, 33])

#### Shuffle the data in x using the values in indices

In [0]:
x[indices]

array([13.41269841, 12.53968254, 10.15873016, 11.42857143, 11.11111111,
       10.        , 14.44444444, 12.14285714, 14.84126984, 10.3968254 ,
       12.06349206, 12.22222222, 13.88888889, 12.46031746, 14.12698413,
       11.74603175, 12.85714286, 10.23809524, 14.36507937, 10.63492063,
       14.6031746 , 11.98412698, 11.34920635, 10.95238095, 12.38095238,
       10.47619048, 13.0952381 , 14.76190476, 11.66666667, 14.04761905,
       15.        , 13.17460317, 10.31746032, 13.80952381, 11.50793651,
       13.65079365, 12.6984127 , 13.01587302, 13.96825397, 14.20634921,
       10.79365079, 13.73015873, 13.49206349, 12.77777778, 14.68253968,
       10.55555556, 10.87301587, 13.57142857, 12.3015873 , 14.92063492,
       11.82539683, 10.71428571, 14.52380952, 14.28571429, 13.33333333,
       12.93650794, 11.03174603, 11.9047619 , 11.58730159, 11.19047619,
       11.26984127, 13.25396825, 10.07936508, 12.61904762])

#### Reshape x into a 3-Dimensional Array

In [0]:
x.reshape(4,4,4)

array([[[10.        , 10.07936508, 10.15873016, 10.23809524],
        [10.31746032, 10.3968254 , 10.47619048, 10.55555556],
        [10.63492063, 10.71428571, 10.79365079, 10.87301587],
        [10.95238095, 11.03174603, 11.11111111, 11.19047619]],

       [[11.26984127, 11.34920635, 11.42857143, 11.50793651],
        [11.58730159, 11.66666667, 11.74603175, 11.82539683],
        [11.9047619 , 11.98412698, 12.06349206, 12.14285714],
        [12.22222222, 12.3015873 , 12.38095238, 12.46031746]],

       [[12.53968254, 12.61904762, 12.6984127 , 12.77777778],
        [12.85714286, 12.93650794, 13.01587302, 13.0952381 ],
        [13.17460317, 13.25396825, 13.33333333, 13.41269841],
        [13.49206349, 13.57142857, 13.65079365, 13.73015873]],

       [[13.80952381, 13.88888889, 13.96825397, 14.04761905],
        [14.12698413, 14.20634921, 14.28571429, 14.36507937],
        [14.44444444, 14.52380952, 14.6031746 , 14.68253968],
        [14.76190476, 14.84126984, 14.92063492, 15.        ]]])

#### Pull the Titanic dataset from the Strata Scratch platform

In [0]:
#code is copy and pasted from the Connect to Strata Scratch with Python.ipynb notebook

!pip install psycopg2
import psycopg2 as ps

/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


In [0]:
host_name = 'db-strata.stratascratch.com'
dbname = 'db_strata'
port = '5432'
user_name = '' #enter username
pwd = '' #enter your database password found in the profile tab in Strata Scratch

try:
    conn = ps.connect(host=host_name,database=dbname,user=user_name,password=pwd,port=port)
except ps.OperationalError as e:
    raise e
else:
    print('Connected!')

Connected!


In [0]:
#Write SQL below to pull datasets 
cur = conn.cursor()
cur.execute(""" 
            SELECT *  FROM titanic; 
            """)
data = cur.fetchall()
colnames = [desc[0] for desc in cur.description] 
conn.commit()

#create the pandas dataframe
data = pd.DataFrame(data)
data.columns = colnames

#close the connection
cur.close()

#### Investigate the DataFrame (e.g., Check first 5 rows of data, data types and review any summary statistics)

In [0]:
data.head()

passengerid  survived  pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                name     sex age  sibsp  \
0                            Braund, Mr. Owen Harris    male  22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38      1   
2                             Heikkinen, Miss. Laina  female  26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35      1   
4                           Allen, Mr. William Henry    male  35      0   

   parch            ticket     fare cabin embarked  
0      0         A/5 21171   7.2500  None        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  None        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  None        S

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
passengerid    891 non-null int64
survived       891 non-null int64
pclass         891 non-null int64
name           891 non-null object
sex            891 non-null object
age            714 non-null object
sibsp          891 non-null int64
parch          891 non-null int64
ticket         891 non-null object
fare           891 non-null float64
cabin          204 non-null object
embarked       889 non-null object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.6+ KB


In [0]:
# the .T will transpose a dataframe
data.describe().T

count        mean         std  min       25%       50%    75%  \
passengerid  891.0  446.000000  257.353842  1.0  223.5000  446.0000  668.5   
survived     891.0    0.383838    0.486592  0.0    0.0000    0.0000    1.0   
pclass       891.0    2.308642    0.836071  1.0    2.0000    3.0000    3.0   
sibsp        891.0    0.523008    1.102743  0.0    0.0000    0.0000    1.0   
parch        891.0    0.381594    0.806057  0.0    0.0000    0.0000    0.0   
fare         891.0   32.204208   49.693429  0.0    7.9104   14.4542   31.0   

                  max  
passengerid  891.0000  
survived       1.0000  
pclass         3.0000  
sibsp          8.0000  
parch          6.0000  
fare         512.3292

#### What was the survival rate for men over the age of 50 in first class?

The survival rate is calculated as the mean of the survived column.

To have a survival rate which is based on some parameters we need to filter the values in that column and then take the mean.

Our filter in this case is predicate made by AND-ing 3 predicates.

The first predicate is `data.sex == 'male'`, second one is `data.age > 50` and third one is `data.pcall == 1`

The key to solving any exercise like this one is to look at the columns and the values each column can take and think of the final predicate in terms of AND, OR and NOT (you can use `~predicate_array` to obtain a logical inversion of the predicate).

First we find all men using `data.sex == 'male'`.

Then we need to find all over the age of 50. We do that by using `data.age > 50`. 

To answer the question all mean over the age of 50 we combine the two predicates with &.

Finally we also answer the question of being in the first class via the predicate `data.pclass==1`.

In the end we answer the whole question by & the results of the first two predicate and the third one.

In [0]:
data['survived'][(data.sex=='male')&(data.age>50)&(data.pclass==1)].mean()

0.19230769230769232

#### Using groupby, count the number of passengers by Sex, Pclass and Survived (Hint: use three columns for group by)

This is similar to the following SQL query.

`SELECT COUNT(passengerid)
FROM titanic
GROUPBY sex, pclass, survived`

In [0]:
data.groupby(['sex','pclass','survived'])[['passengerid']].count()

passengerid
sex    pclass survived             
female 1      0                   3
              1                  91
       2      0                   6
              1                  70
       3      0                  72
              1                  72
male   1      0                  77
              1                  45
       2      0                  91
              1                  17
       3      0                 300
              1                  47

#### Create a pipe delimited csv with only the names and ages of the 10 oldest surivors.

Finding 10 oldest means taking the first ten rows of a dataframe after sorting by age in a descending order.

But first we need to find the survivors which is what line 1 does.

Line 2 sorts the data so on line 3 we can take the first 10 using `.iloc[:10]` (reember `:10` is short for `0:10`)

On line 3 we also take only the name and age columns.

Finally on line 4 we write the output to csv using the pipe as column separator (`sep='|'`).

`index=False` means that the dataframe index will not be written to the file. 

In [0]:
survivors = data[data.survived==1]
survivors.sort_values('age',ascending=False, inplace=True)
top_survivors = survivors[['name','age']].iloc[:10]
top_survivors.to_csv('titanic_10_oldest_survivors.csv', sep='|',index=False)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


**Perform an `ls` to see if the file was created**

In [0]:
!ls

datalab  titanic_10_oldest_survivors.csv


**Download the file to your local computer**

In [0]:
from google.colab import files
files.download('titanic_10_oldest_survivors.csv')